services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest_blog
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
# Top-level volumes key to define the named volumes
volumes:
  postgres_data:
  redis_data:
